### ISSUE TITLE
Traction & Revival

### ISSUE THREAD

**Issue by pyronaur** [zamoose/themehookalliance#44]
Howdy!
It seems that there was *some* traction for THA, but it appears that it didn't gain the necessary momentum. I'm 2 years late, but I'd like to help out in any way I can if necessary.

I'm currently working on a starter theme (releasing it today or tomorrow), which I intend to use to build 26 free WordPress themes. I'd like to make them all support THA because this does seem like a really good idea to me at the moment.

So - my question is this - 
**Why is there in traction in Theme Hook Alliance?** Can we fix that?
Before I commit to implementing this in my starter and all the themes - I'd like to know whether it actually is a good idea or it only seemed to be a good idea at the time.

If it is still a good idea - I think there are a lot of things that we can do to promote THA to theme and plugin developers.

**Comment by Hube2** [comment]
I think it's still a good idea even 1.5 years after you asked this question and it appears that the idea has died. 

I find in infuriating that there are theme developers that do not provide for some things, simple things, like not being able to add Google Tag Manager to a site simply because they don't provide any hook after the `<body>` tag. Some of the other hooks are not as important. Some theme devs use something else, I don't really care what the hook is but there are just some that are needed that WP is never going to supply because, well, I'll keep that comment to myself. 

I mean this is just one example, but anyone that's still using GA code is living in the past and has simply not kept up.

Even if you don't use this exact idea, hooks where other developers will likely need them will always be a good idea.

**Comment by DangitRick** [comment]
Even later still, but I've thought THA was a great idea for a while now. Support is built into my WordPress plugin, OpenHook, which allows customizing any and all hooks from within the admin panel. I'd love to see more themes incorporate the THA hooks. It would make so many customizations portable between theme changes! 

Sadly, it looks as though "full site editing" is replacing actual customization, leaving users with a handful of blocks to play with rather than allowing them the freedom to truly customize things.

**Comment by pyronaur** [comment]
What a blast from the past! I'm pretty sure this isn't happening. 🙂 _(self-closing)_

**Comment by webmandesign** [comment]
@DangitRick Just a shameless plug here: all of [my themes](https://www.webmandesign.eu/project-type/themes/) are compatible with THA hooks. And I've created a [plugin adding a THA hook block](https://github.com/webmandesign/action-hook-block) - just in case this is useful for someone.
